/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.repaymenttracker;

import javax.swing.JOptionPane;

/**
 *
 * @author lloyd
 */
public class ProfilePage extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProfilePage
     */
    public ProfilePage() {
        initComponents();
        
        firstNameTextField.setEditable(false);
        middleNameTextField.setEditable(false);
        lastNameTextField.setEditable(false);
        birthdateFormattedTextField.setEditable(false);
        contactNumberTextField.setEditable(false);
        nationalityTextField.setEditable(false);
        homeAddressTextArea.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        emailAddressTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        middleNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nationalityTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        contactNumberTextField = new javax.swing.JTextField();
        birthdateFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        homeAddressTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fNameEditButton = new javax.swing.JLabel();
        mNameEditButton = new javax.swing.JLabel();
        lNameEditButton = new javax.swing.JLabel();
        nationalityEditButton = new javax.swing.JLabel();
        contactNumberEditButton = new javax.swing.JLabel();
        emailAddressEditButton = new javax.swing.JLabel();
        homeAddressEditButton = new javax.swing.JLabel();
        contactNumberDisplayField = new javax.swing.JTextField();
        userNameDisplayField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(650, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 490));

        updateButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        updateButton.setText("UPDATE INFORMATION");
        updateButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel1.setText("First Name");

        firstNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel3.setText("Middle Name");

        emailAddressTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddressTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel4.setText("Email Address");

        middleNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        middleNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel5.setText("Nationality");

        nationalityTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nationalityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel6.setText("Birthdate");

        contactNumberTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTextFieldActionPerformed(evt);
            }
        });

        birthdateFormattedTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birthdateFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateFormattedTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel7.setText("Contact Number");

        homeAddressTextArea.setColumns(20);
        homeAddressTextArea.setRows(5);
        jScrollPane1.setViewportView(homeAddressTextArea);

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel8.setText("Current Home Address");

        lastNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel9.setText("Last Name");

        fNameEditButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\lloyd\\OneDrive\\Documents\\NetBeansProjects\\repaymentTracker\\src\\main\\java\\com\\mycompany\\repaymenttracker\\Images\\editButton.png")); // NOI18N
        fNameEditButton.setText("jL");
        fNameEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fNameEditButtonMouseClicked(evt);
            }
        });

        mNameEditButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\lloyd\\OneDrive\\Documents\\NetBeansProjects\\repaymentTracker\\src\\main\\java\\com\\mycompany\\repaymenttracker\\Images\\editButton.png")); // NOI18N
        mNameEditButton.setText("jL");
        mNameEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mNameEditButtonMouseClicked(evt);
            }
        });

        lNameEditButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\lloyd\\OneDrive\\Documents\\NetBeansProjects\\repaymentTracker\\src\\main\\java\\com\\mycompany\\repaymenttracker\\Images\\editButton.png")); // NOI18N
        lNameEditButton.setText("jL");
        lNameEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lNameEditButtonMouseClicked(evt);
            }
        });

        nationalityEditButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\lloyd\\OneDrive\\Documents\\NetBeansProjects\\repaymentTracker\\src\\main\\java\\com\\mycompany\\repaymenttracker\\Images\\editButton.png")); // NOI18N
        nationalityEditButton.setText("jL");
        nationalityEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nationalityEditButtonMouseClicked(evt);
            }
        });

        contactNumberEditButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\lloyd\\OneDrive\\Documents\\NetBeansProjects\\repaymentTracker\\src\\main\\java\\com\\mycompany\\repaymenttracker\\Images\\editButton.png")); // NOI18N
        contactNumberEditButton.setText("jL");
        contactNumberEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactNumberEditButtonMouseClicked(evt);
            }
        });

        emailAddressEditButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\lloyd\\OneDrive\\Documents\\NetBeansProjects\\repaymentTracker\\src\\main\\java\\com\\mycompany\\repaymenttracker\\Images\\editButton.png")); // NOI18N
        emailAddressEditButton.setText("jL");
        emailAddressEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailAddressEditButtonMouseClicked(evt);
            }
        });

        homeAddressEditButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\lloyd\\OneDrive\\Documents\\NetBeansProjects\\repaymentTracker\\src\\main\\java\\com\\mycompany\\repaymenttracker\\Images\\editButton.png")); // NOI18N
        homeAddressEditButton.setText("jL");
        homeAddressEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeAddressEditButtonMouseClicked(evt);
            }
        });

        contactNumberDisplayField.setEditable(false);
        contactNumberDisplayField.setBackground(new java.awt.Color(102, 102, 102));
        contactNumberDisplayField.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        contactNumberDisplayField.setForeground(new java.awt.Color(255, 255, 255));
        contactNumberDisplayField.setText("(contact Number should be here)");
        contactNumberDisplayField.setBorder(null);
        contactNumberDisplayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberDisplayFieldActionPerformed(evt);
            }
        });

        userNameDisplayField.setEditable(false);
        userNameDisplayField.setBackground(new java.awt.Color(102, 102, 102));
        userNameDisplayField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        userNameDisplayField.setForeground(new java.awt.Color(255, 255, 255));
        userNameDisplayField.setText("(fullname should be here)");
        userNameDisplayField.setBorder(null);
        userNameDisplayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameDisplayFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(userNameDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameTextField)
                                    .addComponent(middleNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(contactNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(birthdateFormattedTextField)
                                    .addComponent(jLabel7)
                                    .addComponent(lastNameTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fNameEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mNameEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lNameEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(emailAddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(nationalityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(emailAddressEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nationalityEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(homeAddressEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(contactNumberDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(userNameDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactNumberDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameEditButton)
                    .addComponent(nationalityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationalityEditButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddressEditButton)
                    .addComponent(mNameEditButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lNameEditButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(birthdateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(contactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contactNumberEditButton)))
                        .addComponent(jScrollPane1))
                    .addComponent(homeAddressEditButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactNumberDisplayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberDisplayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberDisplayFieldActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        UpdatingInfoSplashScreen splash = new UpdatingInfoSplashScreen(() -> {

        firstNameTextField.setEditable(false);
        middleNameTextField.setEditable(false);
        lastNameTextField.setEditable(false);
        birthdateFormattedTextField.setEditable(false);
        contactNumberTextField.setEditable(false);
        nationalityTextField.setEditable(false);
        homeAddressTextArea.setEditable(false);

        JOptionPane.showMessageDialog(this, "Information has been successfully updated!");
    });

    splash.setVisible(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void emailAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressTextFieldActionPerformed

    private void userNameDisplayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameDisplayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameDisplayFieldActionPerformed

    private void middleNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTextFieldActionPerformed

    private void nationalityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityTextFieldActionPerformed

    private void contactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTextFieldActionPerformed

    private void birthdateFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdateFormattedTextFieldActionPerformed

    private void fNameEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNameEditButtonMouseClicked
        firstNameTextField.setEditable(true);
        firstNameTextField.requestFocus(); 
    }//GEN-LAST:event_fNameEditButtonMouseClicked

    private void mNameEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mNameEditButtonMouseClicked
        middleNameTextField.setEditable(true);
        middleNameTextField.requestFocus(); 
    }//GEN-LAST:event_mNameEditButtonMouseClicked

    private void lNameEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lNameEditButtonMouseClicked
        lastNameTextField.setEditable(true);
        lastNameTextField.requestFocus(); 
    }//GEN-LAST:event_lNameEditButtonMouseClicked

    private void contactNumberEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactNumberEditButtonMouseClicked
        contactNumberTextField.setEditable(true);
        contactNumberTextField.requestFocus(); 
    }//GEN-LAST:event_contactNumberEditButtonMouseClicked

    private void nationalityEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nationalityEditButtonMouseClicked
        nationalityTextField.setEditable(true);
        nationalityTextField.requestFocus(); 
    }//GEN-LAST:event_nationalityEditButtonMouseClicked

    private void emailAddressEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailAddressEditButtonMouseClicked
        emailAddressTextField.setEditable(true);
        emailAddressTextField.requestFocus(); 
    }//GEN-LAST:event_emailAddressEditButtonMouseClicked

    private void homeAddressEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeAddressEditButtonMouseClicked
        homeAddressTextArea.setEditable(true);
        homeAddressTextArea.requestFocus(); 
    }//GEN-LAST:event_homeAddressEditButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField birthdateFormattedTextField;
    private javax.swing.JTextField contactNumberDisplayField;
    private javax.swing.JLabel contactNumberEditButton;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JLabel emailAddressEditButton;
    private javax.swing.JTextField emailAddressTextField;
    private javax.swing.JLabel fNameEditButton;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel homeAddressEditButton;
    private javax.swing.JTextArea homeAddressTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNameEditButton;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel mNameEditButton;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JLabel nationalityEditButton;
    private javax.swing.JTextField nationalityTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField userNameDisplayField;
    // End of variables declaration//GEN-END:variables
}
