/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.repaymenttracker;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author lloyd
 */
public class ProfilePage extends javax.swing.JInternalFrame {
     private int userId;
    /**
     * Creates new form ProfilePage
     * @param userId
     */
    public ProfilePage(int userId) {
        this.userId = userId;
        
        initComponents();
        firstNameTextField.setEditable(false);
        middleNameTextField.setEditable(false);
        lastNameTextField.setEditable(false);
        birthdateFormattedTextField.setEditable(false);
        contactNumberTextField.setEditable(false);
        nationalityTextField.setEditable(false);
        emailAddressTextField.setEditable(false);
        employmentStatusComboBox.setEnabled(false);
        validIdTextField.setEditable(false);
        homeAddressTextArea.setEditable(false);
        
        loadUserProfile();
    }
    
    private void loadUserProfile() {
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conn = DBConnection.getConnection();
            String sql = "SELECT b.first_name, b.middle_name, b.last_name, b.birthdate, "
                    + "b.contact_number, b.nationality, b.employment_status, b.home_address, "
                    + "b.valid_id_number, u.email "
                    + "FROM borrowers b "
                    + "JOIN users u ON b.user_id = u.user_id "
                    + "WHERE b.user_id = ?";

            pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, this.userId);

            rs = pstmt.executeQuery();

            if (rs.next()) {
                String firstName = rs.getString("first_name");
                String lastName = rs.getString("last_name");

                userNameDisplayField.setText(firstName + " " + lastName);
                contactNumberDisplayField.setText(rs.getString("contact_number"));

                firstNameTextField.setText(firstName);
                middleNameTextField.setText(rs.getString("middle_name"));
                lastNameTextField.setText(lastName);
                birthdateFormattedTextField.setText(rs.getString("birthdate"));
                contactNumberTextField.setText(rs.getString("contact_number"));
                validIdTextField.setText(rs.getString("valid_id_number"));
                nationalityTextField.setText(rs.getString("nationality"));
                emailAddressTextField.setText(rs.getString("email"));
                homeAddressTextArea.setText(rs.getString("home_address"));

                employmentStatusComboBox.setSelectedItem(rs.getString("employment_status"));

            } else {
                JOptionPane.showMessageDialog(this, "Could not find profile for user ID: " + this.userId, "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error while loading profile.", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    public boolean isValidEmail(String email) {
        return email.matches("^[A-Za-z0-9+_.-]+@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,6}$");
    }

    public boolean isValidDate(String date) {
        try {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            sdf.setLenient(false);
            sdf.parse(date);
            return true;
        } catch (java.text.ParseException e) {
            return false;
        }
    }

    public boolean isValidContact(String contact) {
        return contact.matches("^\\d{7,15}$");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        userNameDisplayField = new javax.swing.JTextField();
        contactNumberDisplayField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        emailAddressTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        middleNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nationalityTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        contactNumberTextField = new javax.swing.JTextField();
        birthdateFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        homeAddressTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fNameEditButton = new javax.swing.JLabel();
        mNameEditButton = new javax.swing.JLabel();
        lNameEditButton = new javax.swing.JLabel();
        nationalityEditButton = new javax.swing.JLabel();
        contactNumberEditButton = new javax.swing.JLabel();
        emailAddressEditButton = new javax.swing.JLabel();
        homeAddressEditButton = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        employmentStatusEditButton = new javax.swing.JLabel();
        employmentStatusComboBox = new javax.swing.JComboBox<>();
        validIdTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        validIdEditButton = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(650, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 490));

        updateButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        updateButton.setText("UPDATE INFORMATION");
        updateButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel1.setText("First Name");

        firstNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        userNameDisplayField.setEditable(false);
        userNameDisplayField.setBackground(new java.awt.Color(102, 102, 102));
        userNameDisplayField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        userNameDisplayField.setForeground(new java.awt.Color(255, 255, 255));
        userNameDisplayField.setText("(fullname should be here)");
        userNameDisplayField.setBorder(null);
        userNameDisplayField.setFocusable(false);
        userNameDisplayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameDisplayFieldActionPerformed(evt);
            }
        });

        contactNumberDisplayField.setEditable(false);
        contactNumberDisplayField.setBackground(new java.awt.Color(102, 102, 102));
        contactNumberDisplayField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contactNumberDisplayField.setForeground(new java.awt.Color(255, 255, 255));
        contactNumberDisplayField.setText("(contact Number should be here)");
        contactNumberDisplayField.setBorder(null);
        contactNumberDisplayField.setFocusable(false);
        contactNumberDisplayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberDisplayFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(contactNumberDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(userNameDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactNumberDisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel3.setText("Middle Name");

        emailAddressTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddressTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel4.setText("Email Address");

        middleNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        middleNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel5.setText("Nationality");

        nationalityTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nationalityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel6.setText("Birthdate");

        contactNumberTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTextFieldActionPerformed(evt);
            }
        });

        birthdateFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        birthdateFormattedTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birthdateFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateFormattedTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel7.setText("Contact Number");

        homeAddressTextArea.setColumns(20);
        homeAddressTextArea.setRows(5);
        jScrollPane1.setViewportView(homeAddressTextArea);

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel8.setText("Current Home Address");

        lastNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel9.setText("Last Name");

        fNameEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editButton.png"))); // NOI18N
        fNameEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fNameEditButtonMouseClicked(evt);
            }
        });

        mNameEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editButton.png"))); // NOI18N
        mNameEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mNameEditButtonMouseClicked(evt);
            }
        });

        lNameEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editButton.png"))); // NOI18N
        lNameEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lNameEditButtonMouseClicked(evt);
            }
        });

        nationalityEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editButton.png"))); // NOI18N
        nationalityEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nationalityEditButtonMouseClicked(evt);
            }
        });

        contactNumberEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editButton.png"))); // NOI18N
        contactNumberEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactNumberEditButtonMouseClicked(evt);
            }
        });

        emailAddressEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editButton.png"))); // NOI18N
        emailAddressEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailAddressEditButtonMouseClicked(evt);
            }
        });

        homeAddressEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editButton.png"))); // NOI18N
        homeAddressEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeAddressEditButtonMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel10.setText("Employment Status");

        employmentStatusEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editButton.png"))); // NOI18N
        employmentStatusEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employmentStatusEditButtonMouseClicked(evt);
            }
        });

        employmentStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unemployed", "Employed", " " }));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 13)); // NOI18N
        jLabel11.setText("Valid I.D. Number");

        validIdEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editButton.png"))); // NOI18N
        validIdEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validIdEditButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameTextField)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(contactNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(birthdateFormattedTextField)
                                    .addComponent(jLabel7)
                                    .addComponent(lastNameTextField)
                                    .addComponent(middleNameTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fNameEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mNameEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lNameEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel11))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nationalityTextField)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(employmentStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(homeAddressEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nationalityEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(employmentStatusEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(emailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emailAddressEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(validIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validIdEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fNameEditButton)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationalityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationalityEditButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(middleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mNameEditButton)
                    .addComponent(emailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddressEditButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(employmentStatusEditButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(employmentStatusComboBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNameEditButton)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(homeAddressEditButton)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthdateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumberEditButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(validIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(validIdEditButton))
                                .addContainerGap(12, Short.MAX_VALUE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactNumberDisplayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberDisplayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberDisplayFieldActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String firstName = firstNameTextField.getText().trim();
        String middleName = middleNameTextField.getText().trim();
        String lastName = lastNameTextField.getText().trim();
        String birthdate = birthdateFormattedTextField.getText().trim();
        String contactNumber = contactNumberTextField.getText().trim();
        String validId = validIdTextField.getText().trim();
        String nationality = nationalityTextField.getText().trim();
        String email = emailAddressTextField.getText().trim();
        String employmentStatus = employmentStatusComboBox.getSelectedItem().toString();
        String homeAddress = homeAddressTextArea.getText().trim();

        if (firstName.isEmpty() || lastName.isEmpty() || contactNumber.isEmpty() || birthdate.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "First Name, Last Name, Contact, Birthdate, and Email cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!isValidDate(birthdate)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid date in YYYY-MM-DD format.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!isValidContact(contactNumber)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid contact number (7 to 15 digits).", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection conn = null;
        PreparedStatement pstmtBorrower = null;
        PreparedStatement pstmtUser = null;

        try {
            conn = DBConnection.getConnection();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Failed to connect to the database.", "Connection Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            conn.setAutoCommit(false);

            String sqlBorrower = "UPDATE borrowers SET first_name=?, middle_name=?, last_name=?, birthdate=?, "
                    + "contact_number=?, nationality=?, employment_status=?, home_address=?, valid_id_number=? "
                    + "WHERE user_id = ?";
            pstmtBorrower = conn.prepareStatement(sqlBorrower);
            pstmtBorrower.setString(1, firstName);
            pstmtBorrower.setString(2, middleName);
            pstmtBorrower.setString(3, lastName);
            pstmtBorrower.setString(4, birthdate);
            pstmtBorrower.setString(5, contactNumber);
            pstmtBorrower.setString(6, nationality);
            pstmtBorrower.setString(7, employmentStatus);
            pstmtBorrower.setString(8, homeAddress);
            pstmtBorrower.setString(9, validId);
            pstmtBorrower.setInt(10, this.userId); // The crucial WHERE clause
            pstmtBorrower.executeUpdate();

            String sqlUser = "UPDATE users SET email=? WHERE user_id=?";
            pstmtUser = conn.prepareStatement(sqlUser);
            pstmtUser.setString(1, email);
            pstmtUser.setInt(2, this.userId);
            pstmtUser.executeUpdate();

            conn.commit();

            UpdatingInfoSplashScreen splash = new UpdatingInfoSplashScreen(() -> {
                firstNameTextField.setEditable(false);
                middleNameTextField.setEditable(false);
                lastNameTextField.setEditable(false);
                birthdateFormattedTextField.setEditable(false);
                contactNumberTextField.setEditable(false);
                nationalityTextField.setEditable(false);
                emailAddressTextField.setEditable(false);
                employmentStatusComboBox.setEnabled(false);
                validIdTextField.setEditable(false);
                homeAddressTextArea.setEditable(false);

                loadUserProfile();

                JOptionPane.showMessageDialog(this, "Information has been successfully updated!");
            });

            splash.setVisible(true);

        } catch (SQLException e) {
            if (conn != null) {
                try {
                    conn.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }

            if (e.getErrorCode() == 1062) {
                JOptionPane.showMessageDialog(this, "The email address '" + email + "' is already in use by another account.", "Update Failed", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "A database error occurred during the update.", "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } finally {
            try {
                if (pstmtBorrower != null) {
                    pstmtBorrower.close();
                }
                if (pstmtUser != null) {
                    pstmtUser.close();
                }
                if (conn != null) {
                    conn.setAutoCommit(true);
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void emailAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressTextFieldActionPerformed

    private void userNameDisplayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameDisplayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameDisplayFieldActionPerformed

    private void middleNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameTextFieldActionPerformed

    private void nationalityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityTextFieldActionPerformed

    private void contactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTextFieldActionPerformed

    private void birthdateFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdateFormattedTextFieldActionPerformed

    private void fNameEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fNameEditButtonMouseClicked
        firstNameTextField.setEditable(true);
        firstNameTextField.requestFocus(); 
    }//GEN-LAST:event_fNameEditButtonMouseClicked

    private void mNameEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mNameEditButtonMouseClicked
        middleNameTextField.setEditable(true);
        middleNameTextField.requestFocus(); 
    }//GEN-LAST:event_mNameEditButtonMouseClicked

    private void lNameEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lNameEditButtonMouseClicked
        lastNameTextField.setEditable(true);
        lastNameTextField.requestFocus(); 
    }//GEN-LAST:event_lNameEditButtonMouseClicked

    private void contactNumberEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactNumberEditButtonMouseClicked
        contactNumberTextField.setEditable(true);
        contactNumberTextField.requestFocus(); 
    }//GEN-LAST:event_contactNumberEditButtonMouseClicked

    private void nationalityEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nationalityEditButtonMouseClicked
        nationalityTextField.setEditable(true);
        nationalityTextField.requestFocus(); 
    }//GEN-LAST:event_nationalityEditButtonMouseClicked

    private void emailAddressEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailAddressEditButtonMouseClicked
        emailAddressTextField.setEditable(true);
        emailAddressTextField.requestFocus(); 
    }//GEN-LAST:event_emailAddressEditButtonMouseClicked

    private void homeAddressEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeAddressEditButtonMouseClicked
        homeAddressTextArea.setEditable(true);
        homeAddressTextArea.requestFocus(); 
    }//GEN-LAST:event_homeAddressEditButtonMouseClicked

    private void employmentStatusEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employmentStatusEditButtonMouseClicked
        employmentStatusComboBox.setEditable(true);
        employmentStatusComboBox.setEnabled(true);
        employmentStatusComboBox.requestFocus(); 
    }//GEN-LAST:event_employmentStatusEditButtonMouseClicked

    private void validIdEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validIdEditButtonMouseClicked
        validIdTextField.setEditable(true);
        validIdTextField.requestFocus(); 
    }//GEN-LAST:event_validIdEditButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField birthdateFormattedTextField;
    private javax.swing.JTextField contactNumberDisplayField;
    private javax.swing.JLabel contactNumberEditButton;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JLabel emailAddressEditButton;
    private javax.swing.JTextField emailAddressTextField;
    private javax.swing.JComboBox<String> employmentStatusComboBox;
    private javax.swing.JLabel employmentStatusEditButton;
    private javax.swing.JLabel fNameEditButton;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel homeAddressEditButton;
    private javax.swing.JTextArea homeAddressTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNameEditButton;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel mNameEditButton;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JLabel nationalityEditButton;
    private javax.swing.JTextField nationalityTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField userNameDisplayField;
    private javax.swing.JLabel validIdEditButton;
    private javax.swing.JTextField validIdTextField;
    // End of variables declaration//GEN-END:variables
}
